# Makefile for generating report for <CONFIG_CASE>
# $Id$
# -----------------------------------------------------

report: 
	latex  <CONFIG_CASE>_report.tex

pdf:
	pdflatex <CONFIG_CASE>_report.tex
clean:
	\rm -f *~ *.log *.aux *.dvi *.out
	cd TexFiles ; \rm -f *~ *.log *.aux *.dvi *.out
